### ISSUE TITLE
Rerun doesn't run with arguments again

### ISSUE THREAD

**Issue by anlima** [tusharvjoshi/nbrunwithargs#4]
When using "Run with arguments", then stopping the application and trying to restart it again with the "Rerun" button in the output window, the main class from the project properties is run instead.

**Comment by tusharvjoshi** [comment]
Ant based Java projects have a concept of one mail class per project which is marked in the Project Properties dialog box.  If Run File with arguments is used for such a marked main class then this re-run feature works.

It does not work only for the class which is not marked as main class in project.  A workaround for this re-run issue is to mark the required class as main class in the project properties and then run the class with arguments.

Currently this module makes the required class main class for one time and resets it again back to the earlier main class to keep the marked main class of the project as it was earlier hence  fix for a single file for re-runs without marking it main class is not possible.
